### ISSUE TITLE
support for arm64 for raspberry pi

### ISSUE THREAD

**Issue by lucasdidur** [dnsforge-repo/xteve#2]
Hello, 

Could you add support for arm64? xTeVe already has support for the version 

https://xteve.de/download/xteve_2_linux_arm64.zip

**Comment by dnsforge-repo** [comment]
Unfortunately I don't think there is enough demand to support an ARM build of the dnsforge docker.  Even the latest raspberry pi has an intel processor, but we will keep it in mind!

**Comment by dnsforge-repo** [comment]
Will continue to consider ARM support in the future if there is enough demand.

**Comment by alpe12** [comment]
> Even the latest raspberry pi has an intel processor
It doesn't.

> I don't think there is enough demand
For me ARM is the perfect place for this project. But ok. :/

**Comment by 91ajames** [comment]
I would love this run on RasbPi, even on armfh. really dont want to run xteve on my pc.

**Comment by lucasdidur** [comment]
@dnsforge-repo Any update about consider ARM support?

**Comment by chenks** [comment]
would also like to have an arm64/v8 version of this so i can run on a pi4 rather than on NAS.

**Comment by akosveres** [comment]
+1 for ARM support

**Comment by akosveres** [comment]
I just forked the project and built for ARM64, you can see the container here: https://github.com/akosveres/xteve/pkgs/container/xteve

@dnsforge-repo would you be interested in a PR? I know you're pushing to docker hub, my solution uses github packages. I just wanted a quick solution to verify if it would work.

**Comment by chenks** [comment]
> I just forked the project and built for ARM64, you can see the container here: https://github.com/akosveres/xteve/pkgs/container/xteve-arm64
> 
> @dnsforge-repo would you be interested in a PR? I know you're pushing to docker hub, my solution uses github packages. I just wanted a quick solution to verify if it would work.

ooh nice, does this still work and still active?

**Comment by chenks** [comment]
> I just forked the project and built for ARM64, you can see the container here: https://github.com/akosveres/xteve/pkgs/container/xteve-arm64
> 
> @dnsforge-repo would you be interested in a PR? I know you're pushing to docker hub, my solution uses github packages. I just wanted a quick solution to verify if it would work.

guide2go doesn't work, it errors when trying to configure it.

```
/home/xteve/bin/guide2go: line 1: ELF: not found
/home/xteve/bin/guide2go: line 2: @%: not found
/home/xteve/bin/guide2go: line 3: syntax error: unexpected word (expecting ")")
```

did send you a tweet about it, but got no response

**Comment by akosveres** [comment]
@chenks just looking at this.

Seems the guide2go binary is 3 years old and it's not the arm64 version. guide2go has received a lot of updates during those times, will try and figure out a way to get an arm64 binary.

Very sorry for the late reply.

**Comment by akosveres** [comment]
@chenks try https://github.com/akosveres/xteve/pkgs/container/xteve-arm64, I pushed the latest image with an arm64 version of guide2go.

**Comment by chenks** [comment]
@akosveres hi, pulled the new image and set it from scratch.
whilst i no longer get an error when trying to run `guide2conf`, it still doesn't seem to be doing what it should

this is what happens when i try to run the command to create a new epg file
```
0c6cee7f3210:/home/xteve# guide2conf --username ***** --password ***** --max-days 7 --name skyq

Do you want to download the guide data for this lineup?
Enter Y|N|Q: 
```
it jumps straight to the "do you want to down the guide data", but it should go thru the initial setup first, which it isn't doing

not sure if @dnsforge-repo can suggest if something else is going wrong?

**Comment by akosveres** [comment]
Unfortunately, this is where my knowledge dies. I don't use guide2conf so I don't know what's supposed to happen and when. Check maybe some logs, try and get help from the guide2conf repository, those are my best advice in this situation. Sorry I couldn't be of much help.

**Comment by chenks** [comment]
damn, without guide2go working it means i can't use it, otherwise i'd have no epg data

**Comment by dnsforge-repo** [comment]
> Unfortunately, this is where my knowledge dies. I don't use guide2conf so I don't know what's supposed to happen and when. Check maybe some logs, try and get help from the guide2conf repository, those are my best advice in this situation. Sorry I couldn't be of much help.

@akosveres @chenks Check $XTEVE_BIN/guide2go exists and is a compiled arm64 binary.  guide2conf is a perl wrapper for guide2go, so the guide2go binary must exist and be capable of execution.  You can also try testing with the guide2go binary directly ie guide2go -configure /home/xteve/guide2go/conf/skyq.yaml

**Comment by chenks** [comment]
@akosveres @dnsforge-repo 
i've checked $XTEVE_BIN/guide2go and it exists, not sure how to check if it's a compiled arm64 binary though

this is what happened when i tried to run the guide2go binary directly

```
0c6cee7f3210:/home/xteve/bin# ls
guide2conf        guide2go          xteve             xteve_starter.pl  zap2xml.pl
0c6cee7f3210:/home/xteve/bin# guide2go -configure /home/xteve/guide2go/conf/skyq.yaml
bash: /home/xteve/bin/guide2go: cannot execute: required file not found
0c6cee7f3210:/home/xteve/bin# 
```

**Comment by dnsforge-repo** [comment]
You can use the command "file /home/xteve/bin/guide2go" to get information on the compiled binary.   Looks like a broken guide2go binary.

**Comment by chenks** [comment]
> You can use the command "file /home/xteve/bin/guide2go" to get information on the compiled binary. Looks like a broken guide2go binary.

```
0c6cee7f3210:/home/xteve# file /home/xteve/bin/guide2go
/home/xteve/bin/guide2go: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, Go BuildID=7IrV5TEhv2aubuonom4o/W5FucEEzKhVaoZxyV51z/BmTGqMN6qYkQmdtkPSE7/6oD5aPOL-AtF-wQTQPp1, not stripped
```

**Comment by chenks** [comment]
@dnsforge-repo @akosveres 
is there anything else i can do here?

not sure if the command above shows if the binary is broken or not?
